remote_theme : daviddarnes/alembic@main
plugins :
- jekyll-remote-theme



title : Indian classical musical instrument recognizer
description : An image classification API that can identify ten different indian classical musical instruments

author :
  name : Moinul Hossain Dhrubo

sass:
  style: :compressed